set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

# Local build artifacts (generated by esbuild) get written to repo root:
# - main.js
# - styles.css
#
# This repo's Obsidian test vault points at `output/` via a symlink, so we copy
# the generated artifacts into `output/` after building.

TEST_VAULT := "/home/l8ng/Projects/__straydragon__/local-ob-plugin-testing"
PLUGIN_DIRNAME := "obsidian-file-explorer-plus"
OUTPUT_DIR := "output/" + PLUGIN_DIRNAME

build:
  cd "{{justfile_directory()}}" && pnpm build

output: build
  cd "{{justfile_directory()}}" && mkdir -p {{OUTPUT_DIR}} && cp -f main.js styles.css manifest.json {{OUTPUT_DIR}}/

link-test vault=TEST_VAULT:
  mkdir -p "{{vault}}/.obsidian/plugins" && ln -snf "{{justfile_directory()}}/{{OUTPUT_DIR}}" "{{vault}}/.obsidian/plugins/{{PLUGIN_DIRNAME}}"

test: output link-test
